### PR TITLE
installed punkt data

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by dmalan** [comment]
Was this not in the other PR?

**Comment by kzidane** [comment]
That's for ECS not the IDE.

**Comment by dmalan** [comment]
Why does ECS need?

**Comment by kzidane** [comment]
@brianyu28 asked for. I suppose for checks?

**Comment by brianyu28** [comment]
Yeah @dmalan @kzidane we'll need it to test `sentences` in check50

**Comment by dmalan** [comment]
ah makes sense

**Pull request merged**
