### PR TITLE
added valgrind wrapper

### PR DESCRIPTION
**Pull request by kzidane**
@dmalan worth handling shebangs?

### CODE REVIEW

**Comment by dmalan** [comment]
Would a more generalized solution to be to use, e.g., `file` and check for a compiled binary?

```
$ clang -o foo foo.c
$ file foo
foo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, with debug_info, not stripped
```

**Comment by kzidane** [comment]
Was trying to avoid having to extract the argument that represents the executable.

**Comment by dmalan** [comment]
Isn't that just going to be in `$1`?

**Comment by kzidane** [comment]
Are we assuming that users won't add valgrind command-line arguments?

**Comment by dmalan** [comment]
Sorry for missing this!

**Pull request merged**
