### PR TITLE
Add CS50 compilation preferences

### PR DESCRIPTION
**Pull request by tlively**

### CODE REVIEW

**Comment by tlively** [comment]
Should fix https://github.com/cs50/cli50/issues/16

**Comment by tlively** [comment]
@dmalan @brianyu28 Is this a change we want to make?

**Comment by dmalan** [comment]
Addressing as we speak, actually! This change'll be part of a transition from a `root` to `ubuntu` user, which is why `CC` et al. weren't yet baked in. Should be ready shortly.

**Comment by dmalan** [comment]
Implemented this a bit differently, but if you do a `sudo pip install --upgrade cli50` on your machine  later today, it should pull the update!

https://github.com/cs50/cli/blob/ubuntu/etc/profile.d/cli.sh#L21-L26

**Comment by dmalan** [comment]
Good to go.

**Pull request closed without merging**
