### PR TITLE
fixated pip versions

### PR DESCRIPTION
**Pull request by dmalan**

### CODE REVIEW

**Comment by dmalan** [comment]
@kzidane did you want fixating versions?

**Comment by kzidane** [comment]
I think this is not at important now that the images themselves are versioned and that fixates versions automatically. They just won't be visible in `Dockerfile`s. If something goes wrong, we can just set `latest` to the previous version and use that. That makes it easier for us so we don't have to manage the versions of all packages except the ones we need to. We can still merge if you think it's worth it or see another benefit.

**Comment by dmalan** [comment]
Hm, though if we trigger a rebuild of `cs50/cli` on Travis, its version will stay the same but the versions of packages it installs might change?

**Comment by kzidane** [comment]
No, every master build that success should publish a new version.

**Pull request closed without merging**
