### PR TITLE
Add style50 checks

### PR DESCRIPTION
**Pull request by crossroads1112**
Dockerfile now installs `astyle` via apt and `style50` via `pip`. `check50-wrapper` now runs style50 on code and adds score to payload sent to cs50.me

### CODE REVIEW

**Comment by crossroads1112** [comment]
style50 no longer assumes . when run with no args per https://github.com/cs50/style50/pull/15

**Comment by kzidane** [comment]
@crossroads1112 should we change `.` to `*.c *.h *.py` to avoid having `style50` try to look unsupported files (e.g., `.git*`, `Makefile`s, `questions.txt`)? 

```
++ style50 --output=score .
unknown file type "./Makefile", skipping...
unknown file type "./questions.txt", skipping...
unknown file type "./.git/HEAD", skipping...
unknown file type "./.git/config", skipping...
unknown file type "./.git/index", skipping...
unknown file type "./.git/packed-refs", skipping...
unknown file type "./.git/description", skipping...
unknown file type "./.git/refs/remotes/origin/HEAD", skipping...
unknown file type "./.git/refs/heads/cs50/2017/x/fifteen", skipping...
unknown file type "./.git/objects/59/e0ba215bba89aa7bb6ad102287e21e438840b2", skipping...
unknown file type "./.git/objects/pack/pack-763a0538a32fe265a6e149d782f9bdc41801488f.idx", skipping...
unknown file type "./.git/objects/pack/pack-763a0538a32fe265a6e149d782f9bdc41801488f.pack", skipping...
unknown file type "./.git/hooks/pre-applypatch.sample", skipping...
unknown file type "./.git/hooks/pre-push.sample", skipping...
unknown file type "./.git/hooks/post-update.sample", skipping...
unknown file type "./.git/hooks/pre-receive.sample", skipping...
unknown file type "./.git/hooks/applypatch-msg.sample", skipping...
unknown file type "./.git/hooks/prepare-commit-msg.sample", skipping...
unknown file type "./.git/hooks/update.sample", skipping...
unknown file type "./.git/hooks/pre-commit.sample", skipping...
unknown file type "./.git/hooks/pre-rebase.sample", skipping...
unknown file type "./.git/hooks/commit-msg.sample", skipping...
unknown file type "./.git/logs/HEAD", skipping...
unknown file type "./.git/logs/refs/remotes/origin/HEAD", skipping...
unknown file type "./.git/logs/refs/heads/cs50/2017/x/fifteen", skipping...
unknown file type "./.git/info/exclude", skipping...
+ style50_results=0.8605341246290801
```

**Comment by crossroads1112** [comment]
We can, although there's not really reason to. All of those messages go to standard error (and thus are not captured by `$()`) , and there's not that big of an efficiency gain since files with the wrong extension are just skipped.

Also filtering by file extension would mean that `style50` wouldn't check folders. We could use `find` with the `-exec` flag for this but feels a bit overkill.

Another potential problem with that is that any time we add a new language we'll have to change the script (even right now it'd need to be `*.c *.h *.hpp *.cpp *.java *.py *.js`). I could add an option to `style50` to output the file extensions it supports but that also feels a bit like overkill.

If we're worried about crowding the logs, I can suppress those warnings in score mode I suppose.

**Comment by kzidane** [comment]
Waiting on https://github.com/cs50/submit50/pull/134 and https://github.com/cs50/check50/pull/58.

**Pull request merged**
