### PR TITLE
simplified ecs

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by dmalan** [comment]
How come this is in `cs50/cli`? Should it not be in a repo of its own? Or can we just use `cs50/cli` itself for Travis builds and ECS?

**Comment by kzidane** [comment]
We can't use `cs50/cli` for Travis builds, but we're already using a slightly customized version of it for ECS. Now that I think about it, we should probably move this to a separate repo, since we don't really need all the stuff in `cs50/cli` for ECS?

**Comment by dmalan** [comment]
Sounds good, aok to create/migrate!

**Comment by kzidane** [comment]
Moved to cs50/ecs.

**Pull request closed without merging**
